name: Set up project
description: Install dependencies and set up the project
runs:
  using: 'composite'
  steps:
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - name: install
      run: |
        corepack enable pnpm
        pnpm install
      shell: bash
