name: Set up project
description: Install dependencies and set up the project
runs:
  using: 'composite'
  steps:
    - name: pnpm
      uses: pnpm/action-setup@v4
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
    - name: install
      run: pnpm install
      shell: bash
