name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/setup
      - name: Check impact
        if: always()
        run: bin/sync
      - name: Validate image thumbnails
        if: always()
        run: bin/validate-thumbnails

permissions:
  contents: write
